name: rocprofiler-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alabaster=0.7.13=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hd4edc92_1
  - babel=2.12.1=pyhd8ed1ab_1
  - brotli-python=1.1.0=py311hb755f60_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=h0c91306_1017
  - certifi=2023.7.22=pyhd8ed1ab_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - cmake=3.27.4=hcfe8598_4
  - colorama=0.4.6=pyhd8ed1ab_0
  - commonmark=0.9.1=py_0
  - docutils=0.18.1=py311h06a4308_3
  - doxygen=1.9.8=h661eb56_0
  - expat=2.5.0=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.10=h6b639ba_2
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=8.1.0=h28d9a01_0
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h977cf35_4
  - harfbuzz=8.2.0=h3d44ed6_0
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libcurl=8.2.1=hca28451_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_0
  - libgd=2.3.3=h74d50f4_7
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.39=h753d276_0
  - librsvg=2.56.3=h98fae49_0
  - libsqlite=3.43.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_0
  - libtiff=4.5.1=h8b53f26_1
  - libtool=2.4.7=h27087fc_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libwebp=1.3.1=hbf2b3c1_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - markdown=3.4.4=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311h459d7ec_0
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.2=hd590300_0
  - packaging=23.1=pyhd8ed1ab_0
  - pango=1.50.14=ha41ecd1_2
  - pcre2=10.40=hc3806b6_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pygments=2.16.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.5=hab00c5b_0_cpython
  - python_abi=3.11=3_cp311
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - recommonmark=0.7.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rhash=1.4.4=hd590300_0
  - setuptools=68.1.2=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sphinx=7.2.5=pyhd8ed1ab_0
  - sphinx-markdown-tables=0.0.17=pyh6c4a22f_0
  - sphinx_rtd_theme=1.3.0=pyha770c72_0
  - sphinxcontrib-applehelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.5=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.4=pyhd8ed1ab_0
  - sphinxcontrib-jquery=4.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.9=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - click==8.1.7
      - click-log==0.4.0
      - doxysphinx==3.3.4
      - libsass==0.22.0
      - lxml==4.9.3
      - mpire==2.8.0
      - pyjson5==1.6.4
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - six==1.16.0
      - sphinx-markdown==1.0.2
      - sphinxcontrib-doxylink==1.12.2
      - tqdm==4.66.1
